// <auto-generated />
using GreenThumb_Slutprojekt.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenThumb_Slutprojekt.Migrations
{
    [DbContext(typeof(GreenThumbDbContext))]
    [Migration("20231204130713_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GardenModelPlantModel", b =>
                {
                    b.Property<int>("GardensGardenId")
                        .HasColumnType("int");

                    b.Property<int>("PlantsPlantId")
                        .HasColumnType("int");

                    b.HasKey("GardensGardenId", "PlantsPlantId");

                    b.HasIndex("PlantsPlantId");

                    b.ToTable("GardenModelPlantModel");
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.GardenModel", b =>
                {
                    b.Property<int>("GardenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GardenId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GardenId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.InstructionModel", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"), 1L, 1);

                    b.Property<string>("CareDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("care_description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("plant_id");

                    b.HasKey("InstructionId");

                    b.HasIndex("PlantId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            CareDescription = "Roses are deep-rooted plants, so once they have settled in they can usually survive on the moisture naturally present in the soil. However, in hot, dry spells or in dry, sandy soils they may need additional water.",
                            Name = "Watering",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            CareDescription = "Roses are hungry plants and will flower and grow better if given additional feed and mulched with well-rotted manure.",
                            Name = "Feeding",
                            PlantId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            CareDescription = "Avocado plants are best grown in containers in a warm, bright spot indoors. They can also be grown in a heated greenhouse.",
                            Name = "Positioning",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 4,
                            CareDescription = "Water regularly and generously in spring and summer, especially in hot, sunny spells. Reduce watering in winter. See our guide to watering.\r\n\r\nMake sure the \r\n\r\nCan refer to either home-made garden compost or seed/potting compost: • Garden compost is a soil improver made from decomposed plant waste, usually in a compost bin or heap. It is added to soil to improve its fertility, structure and water-holding capacity. Seed or potting composts are used for growing seedlings or plants in containers - a wide range of commercially produced peat-free composts are available, made from a mix of various ingredients, such as loam, composted bark, coir and sand, although you can mix your own.\r\n\r\ncompost is neither excessively wet nor completely dry. The leaves may curl up if the plant is overwatered, and may go brown and drop if underwatered.",
                            Name = "Watering and humidity",
                            PlantId = 2
                        },
                        new
                        {
                            InstructionId = 5,
                            CareDescription = "Water regularly in dry spells during the first two years to aid establishment, especially if planted in spring or later in the season.",
                            Name = "Watering",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 6,
                            CareDescription = "Trees in the open ground rarely need feeding. To prevent trees drying out, and to suppress weeds, \r\n\r\nMulch is a layer of material, at least 5cm (2in) thick, applied to the soil surface in late autumn to late winter (Nov-Feb). It is used to provide frost protection, improve plant growth by adding nutrients or increasing organic matter content, reducing water loss from the soil, for decorative purposes and suppressing weeds. Examples include well-rotted garden compost and manure, chipped bark, gravel, grit and slate chippings.\r\n\r\nmulch with a 10cm (4in) layer of garden \r\n\r\nCan refer to either home-made garden compost or seed/potting compost: • Garden compost is a soil improver made from decomposed plant waste, usually in a compost bin or heap. It is added to soil to improve its fertility, structure and water-holding capacity. Seed or potting composts are used for growing seedlings or plants in containers - a wide range of commercially produced peat-free composts are available, made from a mix of various ingredients, such as loam, composted bark, coir and sand, although you can mix your own.\r\n\r\ncompost or \r\n\r\nMulch is a layer of material, at least 5cm (2in) thick, applied to the soil surface in late autumn to late winter (Nov-Feb). It is used to provide frost protection, improve plant growth by adding nutrients or increasing organic matter content, reducing water loss from the soil, for decorative purposes and suppressing weeds. Examples include well-rotted garden compost and manure, chipped bark, gravel, grit and slate chippings.\r\n\r\nmulching bark. Just make sure the mulch doesn’t butt up to the trunk as this would cause it to rot.",
                            Name = "Feeding",
                            PlantId = 3
                        },
                        new
                        {
                            InstructionId = 7,
                            CareDescription = "Water broccoli \r\n\r\nA seedling is a young plant grown from seed.\r\n\r\nseedlings and young plants regularly until well established.\r\n\r\nAfter that, only water during dry weather, every fortnight or so, to avoid any check in their growth, which can lead to bolting (premature flowering). Take care not to overwater winter varieties, to ensure they cope well with lower temperatures.",
                            Name = "Watering",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 8,
                            CareDescription = "Broccoli is susceptible to all the usual brassica pests, so keep them protected at all times. Insect-proof mesh or fleece, supported on canes and pinned to the ground, should deter cabbage caterpillars, cabbage root fly and pigeons. See Problem solving, below, for more tips.",
                            Name = "Protecting from pests",
                            PlantId = 4
                        },
                        new
                        {
                            InstructionId = 9,
                            CareDescription = "Newly planted gages should be watered regularly for at least their first growing season. Once established, they usually only need watering during dry spells, especially in early to mid-summer when the fruit is swelling. Lack of water may cause the tree to shed young fruit. \r\n\r\nMulch is a layer of material, at least 5cm (2in) thick, applied to the soil surface in late autumn to late winter (Nov-Feb). It is used to provide frost protection, improve plant growth by adding nutrients or increasing organic matter content, reducing water loss from the soil, for decorative purposes and suppressing weeds. Examples include well-rotted garden compost and manure, chipped bark, gravel, grit and slate chippings.\r\n\r\nMulching (see below) will help to stop the soil drying out.\r\n\r\nTo get a successful crop from containerised trees, they must be watered on a regular basis throughout the growing season. The relatively small amount of potting \r\n\r\nCan refer to either home-made garden compost or seed/potting compost: • Garden compost is a soil improver made from decomposed plant waste, usually in a compost bin or heap. It is added to soil to improve its fertility, structure and water-holding capacity. Seed or potting composts are used for growing seedlings or plants in containers - a wide range of commercially produced peat-free composts are available, made from a mix of various ingredients, such as loam, composted bark, coir and sand, although you can mix your own.\r\n\r\ncompost will dry out quickly, especially in warm weather.",
                            Name = "Watering",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 10,
                            CareDescription = "Protecting from frost\r\nGages flower early, so the blossom is vulnerable to frost damage. With smaller trained trees, if frost is forecast during flowering, cover them temporarily in a tent of \r\n\r\nHorticultural fleece is a soft fibrous, translucent material, also known as a crop cover. It is laid over or around vulnerable plants to protect them against the weather (heavier grades of fleece give a about 2°C of protection from frost); pests and to help plants to grow in the warmer conditions underneath.\r\n\r\nhorticultural fleece or hessian, holding it away from the flowers with canes. Remove it during the day, to allow pollinators access.\r\n\r\nIf possible, move potted trees indoors for the night or into a sheltered spot if frosts are due during flowering.",
                            Name = "Protecting from frost",
                            PlantId = 5
                        },
                        new
                        {
                            InstructionId = 11,
                            CareDescription = "Remove flowers on alpine and border plants to encourage further flowering\r\nIf growing Persian buttercups (Ranunculus asiaticus) for the vase, cut the stems before the flowers are fully open and they should last 10-12 days",
                            Name = "Dead heading",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 12,
                            CareDescription = "Most ranunculus are hardy so don't need any special care over winter\r\nGrow Persian buttercups (Ranunculus asiaticus) in a cool greenhouse in winter",
                            Name = "Overwintering",
                            PlantId = 6
                        },
                        new
                        {
                            InstructionId = 13,
                            CareDescription = "Water newly planted lovage regularly for the first few months, until settled in and growing strongly.  \r\n\r\nLike its near-relative celery, lovage likes plenty of moisture in the soil, but not \r\n\r\nDescribes soil or potting compost that is saturated with water. The water displaces air from the spaces between soil particles and plant roots can literally drown, unless they are adapted to growing in waterlogged conditions. Waterlogging is common on poorly drained soil or when heavy soil is compacted. \r\n\r\nwaterlogged conditions. Plants may need additional watering in hot summer weather, especially if growing in full sun or free-draining soil.  ",
                            Name = "Watering",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 14,
                            CareDescription = "Keep young lovage plants weed-free, to reduce competition for light, water and nutrients. Once established, lovage generally forms a robust leafy clump that shades out any nearby weeds. \r\n\r\nGiven the chance, lovage is a prolific self-seeder. So weed out any unwanted \r\n\r\nA seedling is a young plant grown from seed.\r\n\r\nseedlings in early summer, before they get established, or pot them up and share them with friends. Remove the seedheads before they ripen if you want to prevent self-seeding. ",
                            Name = "Weeding",
                            PlantId = 7
                        },
                        new
                        {
                            InstructionId = 15,
                            CareDescription = "Water young \r\n\r\nA seedling is a young plant grown from seed.\r\n\r\nseedlings regularly if conditions are dry. Once established, salsify should only need watering in long dry spells, to prevent the roots splitting.\r\n \r\nIf growing salsify in a container, water regularly throughout the growing season.",
                            Name = "Watering",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 16,
                            CareDescription = "Salsify shouldn’t need any feeding.",
                            Name = "Feeding",
                            PlantId = 8
                        },
                        new
                        {
                            InstructionId = 17,
                            CareDescription = "Once established they are fairly drought tolerant and should not need watering.\r\nHowever, during very dry periods they may need additional water even when established. Signs of water stress are shrivelled leaves with brown edges and leaves falling off the plant.",
                            Name = "Watering",
                            PlantId = 9
                        },
                        new
                        {
                            InstructionId = 18,
                            CareDescription = "Ribes do not need regular feeding, but to encourage vigorous growth after pruning, plants can be fed annually in March/April, with a general purpose fertiliser such as Growmore or fish, blood and bone, or \r\n\r\nMulch is a layer of material, at least 5cm (2in) thick, applied to the soil surface in late autumn to late winter (Nov-Feb). It is used to provide frost protection, improve plant growth by adding nutrients or increasing organic matter content, reducing water loss from the soil, for decorative purposes and suppressing weeds. Examples include well-rotted garden compost and manure, chipped bark, gravel, grit and slate chippings.\r\n\r\nmulch with organic matter.",
                            Name = "Feeding",
                            PlantId = 9
                        },
                        new
                        {
                            InstructionId = 19,
                            CareDescription = "Asters in the ground\r\nWater well after planting. On free-draining soil or during prolonged dry spells, they will need additional water to keep the soil around the roots slightly moist, but not soggy. Aim to water well and occasionally, rather than little and often.\r\n\r\nThe height of an aster can vary from year to year according to the amount of water it has received.\r\n\r\nAsters in containers\r\nThese need more frequent watering than plants growing in the ground. Water as often as needed, which could be daily in hot weather. Try not to let the \r\n\r\nCan refer to either home-made garden compost or seed/potting compost: • Garden compost is a soil improver made from decomposed plant waste, usually in a compost bin or heap. It is added to soil to improve its fertility, structure and water-holding capacity. Seed or potting composts are used for growing seedlings or plants in containers - a wide range of commercially produced peat-free composts are available, made from a mix of various ingredients, such as loam, composted bark, coir and sand, although you can mix your own.\r\n\r\ncompost dry out, but do not let it get waterlogged for more than a day or two either.",
                            Name = "Watering",
                            PlantId = 10
                        },
                        new
                        {
                            InstructionId = 20,
                            CareDescription = "The majority of perennial asters are hardy throughout the UK and can withstand low temperatures. Most species and cultivars of Symphyotrichum can survive temperatures down to -20°C (-4°F).\r\n\r\nWinter wet is more likely to be a problem than cold.\r\n\r\nRemove annual Callistephus chinensis when they finish flowering in late autumn or leave overwinter. Add the old plants to your garden compost heaps. ",
                            Name = "Overwintering",
                            PlantId = 10
                        },
                        new
                        {
                            InstructionId = 21,
                            CareDescription = "Water newly planted foxgloves regularly for at least the first few months, to help them until their roots have spread out into the soil\r\n\r\nOnce established, foxgloves growing in soil that is rich in organic matter should only need watering in long dry spells in summer. Wilting large leaves are a good indicator that plants need a good long soak\r\n\r\nFoxgloves growing in containers need regular watering throughout the growing season, as the \r\n\r\nCan refer to either home-made garden compost or seed/potting compost: • Garden compost is a soil improver made from decomposed plant waste, usually in a compost bin or heap. It is added to soil to improve its fertility, structure and water-holding capacity. Seed or potting composts are used for growing seedlings or plants in containers - a wide range of commercially produced peat-free composts are available, made from a mix of various ingredients, such as loam, composted bark, coir and sand, although you can mix your own.\r\n\r\ncompost will dry out quickly, especially in summer. Aim to keep the compost slightly moist but never waterlogged",
                            Name = "Watering",
                            PlantId = 11
                        },
                        new
                        {
                            InstructionId = 22,
                            CareDescription = "The sturdy flower stems don’t generally require staking if the plant is in a sheltered spot, out of strong winds\r\n\r\nPlants in exposed sites and tall cultivars with larger blooms benefit from support, to prevent the spikes snapping. Use a bamboo \r\n\r\nA cane is a slender, straight, length of woody plant material, usually bamboo. Canes are primarily used as plant supports. The fruiting stems of blackberries, raspberries and hybrid berries (such as loganberries and tayberries) are also known as canes, so these crops are often referred to as cane fruit.\r\n\r\ncane and twine, or a wire support with a loop to hold the stem\r\n\r\nIf growing foxgloves for cut flower arrangements, tying the stem to a support will help to ensure the straight, upright flower spike that is often preferred",
                            Name = "Staking",
                            PlantId = 11
                        },
                        new
                        {
                            InstructionId = 23,
                            CareDescription = "During their first year, kniphofias will need the occasional thorough watering to keep the soil moist\r\n\r\nOnce settled in, they shouldn’t need watering except in prolonged dry spells\r\n\r\nSitting in waterlogged soil can cause the roots to rot, so check that the soil is dry to a depth of 15cm (6in) before watering",
                            Name = "Watering",
                            PlantId = 12
                        },
                        new
                        {
                            InstructionId = 24,
                            CareDescription = "To keep plants looking their best, deadhead after flowering. This also allows newer younger flower stems plenty of space to grow\r\n\r\nSimply cut the whole faded flower stem down at the base\r\n\r\nDeadheading also helps the plant to conserve energy, by stopping seed production. However, if you wish to collect seeds for sowing (see Propagation, below), then leave a few stems in place to set seed",
                            Name = "Deadheading",
                            PlantId = 12
                        });
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.PlantModel", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("PlantId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Name = "Rose"
                        },
                        new
                        {
                            PlantId = 2,
                            Name = "Avocado"
                        },
                        new
                        {
                            PlantId = 3,
                            Name = "Maple tree"
                        },
                        new
                        {
                            PlantId = 4,
                            Name = "Broccoli"
                        },
                        new
                        {
                            PlantId = 5,
                            Name = "Gages"
                        },
                        new
                        {
                            PlantId = 6,
                            Name = "Ranunculus"
                        },
                        new
                        {
                            PlantId = 7,
                            Name = "Loveage"
                        },
                        new
                        {
                            PlantId = 8,
                            Name = "Salsify"
                        },
                        new
                        {
                            PlantId = 9,
                            Name = "Ribes"
                        },
                        new
                        {
                            PlantId = 10,
                            Name = "Asters"
                        },
                        new
                        {
                            PlantId = 11,
                            Name = "Foxgloves"
                        },
                        new
                        {
                            PlantId = 12,
                            Name = "Kniphofia"
                        });
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "password",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("GardenModelPlantModel", b =>
                {
                    b.HasOne("GreenThumb_Slutprojekt.Models.GardenModel", null)
                        .WithMany()
                        .HasForeignKey("GardensGardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenThumb_Slutprojekt.Models.PlantModel", null)
                        .WithMany()
                        .HasForeignKey("PlantsPlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.GardenModel", b =>
                {
                    b.HasOne("GreenThumb_Slutprojekt.Models.UserModel", "User")
                        .WithOne("Garden")
                        .HasForeignKey("GreenThumb_Slutprojekt.Models.GardenModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.InstructionModel", b =>
                {
                    b.HasOne("GreenThumb_Slutprojekt.Models.PlantModel", "Plant")
                        .WithMany("Instructions")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.PlantModel", b =>
                {
                    b.Navigation("Instructions");
                });

            modelBuilder.Entity("GreenThumb_Slutprojekt.Models.UserModel", b =>
                {
                    b.Navigation("Garden");
                });
#pragma warning restore 612, 618
        }
    }
}
